/// Immutable analytics models for the KnightOS engine platform.
///
/// These types provide a generic, strongly typed vocabulary for future modules
/// to expose analytics data without embedding feature-specific logic in the
/// analytics engine itself.
library;

/// Supported time windows for analytics aggregation.
enum KnightAnalyticsTimeRange {
  /// A short rolling window.
  rolling,

  /// Weekly aggregation.
  weekly,

  /// Monthly aggregation.
  monthly,

  /// Yearly aggregation.
  yearly,

  /// A custom range supplied by the caller.
  custom,
}

/// Supported analytics directions for trend interpretation.
enum KnightAnalyticsTrendDirection {
  /// The trend is rising.
  increasing,

  /// The trend is steady.
  stable,

  /// The trend is declining.
  decreasing,
}

/// A single metric value emitted by a future module.
class KnightMetric {
  /// Creates an immutable metric.
  const KnightMetric({
    required this.name,
    required this.value,
    required this.timestamp,
    this.unit,
  });

  /// Name of the metric.
  final String name;

  /// Numeric value of the metric.
  final double value;

  /// Timestamp for the metric sample.
  final DateTime timestamp;

  /// Optional unit such as hours, count, dollars, or percent.
  final String? unit;
}

/// A historical data point for a series.
class KnightHistoricalDataPoint {
  /// Creates an immutable historical data point.
  const KnightHistoricalDataPoint({
    required this.timestamp,
    required this.value,
  });

  /// Timestamp of the data point.
  final DateTime timestamp;

  /// Numeric value of the data point.
  final double value;
}

/// A trend interpretation for a sequence of data.
class KnightTrend {
  /// Creates an immutable trend.
  const KnightTrend({
    required this.direction,
    required this.slope,
    required this.confidence,
    required this.period,
  });

  /// Direction of the trend.
  final KnightAnalyticsTrendDirection direction;

  /// Numeric slope or rate of change.
  final double slope;

  /// Confidence of the trend interpretation.
  final double confidence;

  /// Time period the trend covers.
  final KnightAnalyticsTimeRange period;
}

/// A generic insight generated by the analytics engine.
class KnightInsight {
  /// Creates an immutable insight.
  const KnightInsight({
    required this.title,
    required this.summary,
    required this.severity,
    required this.timestamp,
  });

  /// Short title for the insight.
  final String title;

  /// Summary text describing the insight.
  final String summary;

  /// Severity level associated with the insight.
  final String severity;

  /// Timestamp of the insight.
  final DateTime timestamp;
}

/// Comparison result between two modules or series.
class KnightComparisonResult {
  /// Creates an immutable comparison result.
  const KnightComparisonResult({
    required this.leftLabel,
    required this.rightLabel,
    required this.difference,
    required this.significance,
  });

  /// Label for the left-hand comparison value.
  final String leftLabel;

  /// Label for the right-hand comparison value.
  final String rightLabel;

  /// Numeric difference between the compared values.
  final double difference;

  /// Optional significance qualifier.
  final String? significance;
}

/// Snapshot of analytics analysis for a module or series.
class KnightAnalyticsSnapshot {
  /// Creates an immutable analytics snapshot.
  const KnightAnalyticsSnapshot({
    required this.moduleId,
    required this.timeRange,
    required this.metrics,
    required this.trend,
    required this.average,
    required this.summary,
    required this.timestamp,
  });

  /// Identifier of the module or series being analysed.
  final String moduleId;

  /// Time range used for analysis.
  final KnightAnalyticsTimeRange timeRange;

  /// Metrics included in the analysis.
  final List<KnightMetric> metrics;

  /// Trend derived from the metric history.
  final KnightTrend trend;

  /// Rolling average of the metric history.
  final double average;

  /// Summary text for the snapshot.
  final String summary;

  /// Timestamp when the snapshot was created.
  final DateTime timestamp;
}
