import 'package:flutter/foundation.dart';

/// Categories of user intent detected by the Cognitive Layer.
enum KnightIntent {
  /// Simple question or fact retrieval.
  question,

  /// Request to make or evaluate a choice.
  decision,

  /// Request to create or update a sequence of actions.
  planning,

  /// Request for self-analysis or review.
  reflection,

  /// Request to acquire or process new knowledge.
  learning,

  /// Request to set or check a reminder.
  reminder,

  /// Casual discussion or exploratory talk.
  conversation,

  /// Searching for information across systems.
  search,

  /// Analyzing data for trends or anomalies.
  analysis,
}

/// A structured trace of the reasoning process for a specific conclusion.
@immutable
class ReasoningTrace {
  const ReasoningTrace({
    required this.intent,
    required this.memoriesUsed,
    required this.rulesApplied,
    required this.goalsConsidered,
    required this.thoughtChain,
    required this.confidence,
    this.potentialRisks = const [],
    this.alternatives = const [],
    this.graphPath = const [],
  });

  /// The detected intent that started this trace.
  final KnightIntent intent;

  /// IDs of memories retrieved for context.
  final List<String> memoriesUsed;

  /// IDs of life rules that influenced the outcome.
  final List<String> rulesApplied;

  /// IDs of long-term goals taken into account.
  final List<String> goalsConsidered;

  /// Sequential list of "thoughts" or logical steps.
  final List<String> thoughtChain;

  /// Final confidence score (0.0 to 1.0).
  final double confidence;

  /// Identified risks (used for Knight Challenge Mode).
  final List<String> potentialRisks;

  /// Alternative options identified during reasoning.
  final List<Map<String, dynamic>> alternatives;

  /// Sequential IDs or descriptions of nodes in the causal path.
  final List<String> graphPath;

  ReasoningTrace copyWith({
    KnightIntent? intent,
    List<String>? memoriesUsed,
    List<String>? rulesApplied,
    List<String>? goalsConsidered,
    List<String>? thoughtChain,
    double? confidence,
    List<String>? potentialRisks,
    List<Map<String, dynamic>>? alternatives,
    List<String>? graphPath,
  }) {
    return ReasoningTrace(
      intent: intent ?? this.intent,
      memoriesUsed: memoriesUsed ?? this.memoriesUsed,
      rulesApplied: rulesApplied ?? this.rulesApplied,
      goalsConsidered: goalsConsidered ?? this.goalsConsidered,
      thoughtChain: thoughtChain ?? this.thoughtChain,
      confidence: confidence ?? this.confidence,
      potentialRisks: potentialRisks ?? this.potentialRisks,
      alternatives: alternatives ?? this.alternatives,
      graphPath: graphPath ?? this.graphPath,
    );
  }
}

/// Represents an executable plan generated by Knight.
@immutable
class CognitivePlan {
  const CognitivePlan({
    required this.id,
    required this.title,
    required this.steps,
    required this.targetGoalId,
    this.status = 'draft',
    required this.createdAt,
  });

  final String id;
  final String title;
  final List<String> steps;
  final String targetGoalId;
  final String status;
  final DateTime createdAt;
}

/// Represents a high-level insight discovered by the OS.
@immutable
class CognitiveInsight {
  const CognitiveInsight({
    required this.title,
    required this.description,
    required this.evidenceIds,
    required this.confidence,
    required this.detectedAt,
  });

  final String title;
  final String description;
  final List<String> evidenceIds;
  final double confidence;
  final DateTime detectedAt;
}
