import 'package:flutter/foundation.dart';

/// Represents a source contribution to a context field.
@immutable
class ContextContribution {
  const ContextContribution({
    required this.sourceId,
    required this.field,
    required this.value,
    required this.confidence,
    required this.timestamp,
    this.metadata = const {},
  });

  final String sourceId;
  final String field;
  final dynamic value;
  final double confidence;
  final DateTime timestamp;
  final Map<String, dynamic> metadata;
}

/// The result of a context fusion operation.
@immutable
class ContextFusionResult {
  const ContextFusionResult({
    required this.field,
    required this.fusedValue,
    required this.overallConfidence,
    required this.contributions,
    required this.method,
  });

  final String field;
  final dynamic fusedValue;
  final double overallConfidence;
  final List<ContextContribution> contributions;
  final String method; // e.g., 'latest', 'weighted_average', 'consensus'
}

/// Metadata for context health monitoring.
@immutable
class ContextHealth {
  const ContextHealth({
    required this.overallScore,
    required this.freshnessScores,
    required this.availabilityScores,
  });

  final int overallScore; // 0-100
  final Map<String, double> freshnessScores; // sourceId -> 0.0-1.0
  final Map<String, bool> availabilityScores; // sourceId -> connected?
}

/// A candidate for a memory, generated by the Context Engine.
@immutable
class MemoryCandidate {
  const MemoryCandidate({
    required this.id,
    required this.summary,
    required this.category,
    required this.evidence,
    required this.timestamp,
    this.initialConfidence = 0.5,
  });

  final String id;
  final String summary;
  final String category;
  final Map<String, dynamic> evidence;
  final DateTime timestamp;
  final double initialConfidence;
}

/// A decision input published by the Context Engine.
@immutable
class DecisionInput {
  const DecisionInput({
    required this.id,
    required this.type,
    required this.payload,
    required this.importance,
    required this.timestamp,
  });

  final String id;
  final String type; // e.g., 'low_battery', 'upcoming_meeting', 'health_anomaly'
  final Map<String, dynamic> payload;
  final double importance; // 0.0-1.0
  final DateTime timestamp;
}
