import 'package:flutter/foundation.dart';
import 'package:uuid/uuid.dart';
import 'memory_category.dart';
import 'memory_domain.dart';

/// The reliability state of a piece of knowledge in the OS.
enum KnowledgeState {
  /// Directly imported from a trusted source (Timeline, Financial Statement, etc.)
  observed,

  /// Generated by Knight through reasoning or pattern detection.
  inferred,

  /// Explicitly verified by the owner.
  userConfirmed,

  /// Explicitly rejected or modified by the owner.
  userCorrected,

  /// Previously true but no longer current.
  deprecated,
}

/// Represents the common metadata substrate for every Atomic Memory Unit (AMU).
@immutable
class MemoryMetadata {
  MemoryMetadata({
    String? memoryId,
    String? versionId,
    required this.effectiveAt,
    DateTime? recordedAt,
    required this.confidence,
    required this.source,
    this.provenance = 'local',
    required this.domain,
    required this.category,
    this.isLatest = true,
    this.verified = false,
    this.questionId,
    this.tags = const [],
    this.knowledgeState = KnowledgeState.observed,
    this.explanation,
    DateTime? updatedAt,
    this.lastVerifiedAt,
    this.verificationHistory = const [],
    this.embedding,
    this.semanticMetadata = const {},
  }) : memoryId = memoryId ?? const Uuid().v4(),
       versionId = versionId ?? const Uuid().v4(),
       recordedAt = recordedAt ?? DateTime.now(),
       updatedAt = updatedAt ?? recordedAt ?? DateTime.now();

  /// Logical identifier for the fact chain (Single Source of Truth key).
  final String memoryId;

  /// Unique identifier for this specific version.
  final String versionId;

  /// When the fact became true in reality.
  final DateTime effectiveAt;

  /// When the fact was committed to memory.
  final DateTime recordedAt;

  /// When the fact was last modified.
  final DateTime updatedAt;

  /// Reliability score from 0.0 to 1.0.
  final double confidence;

  /// The origin of the information.
  final MemorySource source;

  /// Detailed string describing the origin of the data.
  final String provenance;

  /// The specific ontology domain.
  final MemoryDomain domain;

  /// The Knowledge Book this belongs to.
  final BookCategory category;

  /// Flag identifying the current state for optimized lookups.
  final bool isLatest;

  /// Whether the owner has explicitly verified this information.
  final bool verified;

  /// When the user last confirmed this memory.
  final DateTime? lastVerifiedAt;

  /// List of verification events.
  final List<Map<String, dynamic>> verificationHistory;

  /// Link back to the specific inquiry in the Question Bank.
  final String? questionId;

  /// Semantic labels.
  final List<String> tags;

  /// Lifecycle state of the knowledge.
  final KnowledgeState knowledgeState;

  /// Human-readable reasoning for inferred knowledge.
  final String? explanation;

  /// Vector representation for semantic search.
  final List<double>? embedding;

  /// Provider and version info for the embedding.
  final Map<String, dynamic> semanticMetadata;

  MemoryMetadata copyWith({
    DateTime? effectiveAt,
    DateTime? updatedAt,
    double? confidence,
    bool? isLatest,
    bool? verified,
    DateTime? lastVerifiedAt,
    List<Map<String, dynamic>>? verificationHistory,
    String? questionId,
    List<String>? tags,
    KnowledgeState? knowledgeState,
    String? explanation,
    String? versionId,
    List<double>? embedding,
    Map<String, dynamic>? semanticMetadata,
    String? provenance,
  }) {
    return MemoryMetadata(
      memoryId: memoryId,
      versionId: versionId ?? this.versionId,
      effectiveAt: effectiveAt ?? this.effectiveAt,
      recordedAt: recordedAt,
      updatedAt: updatedAt ?? this.updatedAt,
      confidence: confidence ?? this.confidence,
      source: source,
      provenance: provenance ?? this.provenance,
      domain: domain,
      category: category,
      isLatest: isLatest ?? this.isLatest,
      verified: verified ?? this.verified,
      lastVerifiedAt: lastVerifiedAt ?? this.lastVerifiedAt,
      verificationHistory: verificationHistory ?? this.verificationHistory,
      questionId: questionId ?? this.questionId,
      tags: tags ?? this.tags,
      knowledgeState: knowledgeState ?? this.knowledgeState,
      explanation: explanation ?? this.explanation,
      embedding: embedding ?? this.embedding,
      semanticMetadata: semanticMetadata ?? this.semanticMetadata,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'memoryId': memoryId,
      'versionId': versionId,
      'effectiveAt': effectiveAt.toIso8601String(),
      'recordedAt': recordedAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'confidence': confidence,
      'source': source.name,
      'provenance': provenance,
      'domainId': domain.id,
      'categoryId': category.id,
      'isLatest': isLatest,
      'verified': verified,
      'lastVerifiedAt': lastVerifiedAt?.toIso8601String(),
      'verificationHistory': verificationHistory,
      'questionId': questionId,
      'tags': tags,
      'knowledgeState': knowledgeState.name,
      'explanation': explanation,
      'embedding': embedding,
      'semanticMetadata': semanticMetadata,
    };
  }

  factory MemoryMetadata.fromJson(Map<String, dynamic> json) {
    return MemoryMetadata(
      memoryId: json['memoryId'] as String,
      versionId: json['versionId'] as String,
      effectiveAt: DateTime.parse(json['effectiveAt'] as String),
      recordedAt: DateTime.parse(json['recordedAt'] as String),
      updatedAt: DateTime.parse(
        json['updatedAt'] as String? ?? json['recordedAt'] as String,
      ),
      confidence: (json['confidence'] as num).toDouble(),
      source: MemorySource.values.byName(json['source'] as String),
      provenance: json['provenance'] as String,
      domain: MemoryDomain.fromId(json['domainId'] as int),
      category: BookCategory.fromId(json['categoryId'] as int),
      isLatest: json['isLatest'] as bool,
      verified: json['verified'] as bool? ?? false,
      lastVerifiedAt: json['lastVerifiedAt'] != null
          ? DateTime.parse(json['lastVerifiedAt'] as String)
          : null,
      verificationHistory:
          (json['verificationHistory'] as List<dynamic>?)
              ?.cast<Map<String, dynamic>>() ??
          const [],
      questionId: json['questionId'] as String?,
      tags: (json['tags'] as List<dynamic>).cast<String>(),
      knowledgeState: KnowledgeState.values.byName(
        json['knowledgeState'] as String? ?? 'observed',
      ),
      explanation: json['explanation'] as String?,
      embedding: (json['embedding'] as List<dynamic>?)?.cast<double>(),
      semanticMetadata:
          (json['semanticMetadata'] as Map<String, dynamic>?) ?? const {},
    );
  }
}
