import 'package:flutter/foundation.dart';

/// Categories for proactive OS notifications.
enum NotificationCategory {
  health,
  finance,
  mission,
  security,
  system,
  world,
}

/// Priority levels for intelligent delivery.
enum NotificationPriority {
  low,
  medium,
  high,
  critical,
}

/// Represents a proactive alert generated by the KnightOS Intelligence Layer.
@immutable
class KnightNotification {
  const KnightNotification({
    required this.id,
    required this.title,
    required this.body,
    required this.category,
    required this.priority,
    required this.timestamp,
    this.actionLabel,
    this.actionRoute,
    this.metadata = const {},
  });

  final String id;
  final String title;
  final String body;
  final NotificationCategory category;
  final NotificationPriority priority;
  final DateTime timestamp;
  final String? actionLabel;
  final String? actionRoute;
  final Map<String, dynamic> metadata;
}
