import 'package:flutter/foundation.dart';
import 'mission_models.dart';
import 'reasoning_models.dart';

/// Represents a specific, quantifiable objective in KnightOS.
@immutable
class KnightGoal {
  const KnightGoal({
    required this.id,
    required this.title,
    required this.description,
    required this.progress,
    required this.priority,
    required this.status,
    required this.targetDate,
  });

  final String id;
  final String title;
  final String description;
  final double progress; // 0.0 to 1.0
  final MissionPriority priority;
  final MissionStatus status;
  final DateTime? targetDate;
}

/// An atomic unit of work generated by the Planning Engine.
@immutable
class KnightTask {
  const KnightTask({
    required this.id,
    required this.title,
    this.description,
    required this.priority,
    required this.isCompleted,
    this.estimatedMinutes,
    this.scheduledStartTime,
    this.category,
    this.dependencyIds = const [],
    this.milestoneId,
    this.isSensitive = false,
    this.fallbackTaskIds = const [],
    this.executionMetadata = const {},
    this.targetDeviceId,
  });

  final String id;
  final String title;
  final String? description;
  final MissionPriority priority;
  final bool isCompleted;
  final int? estimatedMinutes;
  final DateTime? scheduledStartTime;
  final String? category;
  final List<String> dependencyIds;
  final String? milestoneId;
  final bool isSensitive;
  final List<String> fallbackTaskIds;
  final Map<String, dynamic> executionMetadata;
  final String? targetDeviceId;

  KnightTask copyWith({
    bool? isCompleted,
    List<String>? dependencyIds,
    bool? isSensitive,
    List<String>? fallbackTaskIds,
    Map<String, dynamic>? executionMetadata,
    String? targetDeviceId,
  }) {
    return KnightTask(
      id: id,
      title: title,
      description: description,
      priority: priority,
      isCompleted: isCompleted ?? this.isCompleted,
      estimatedMinutes: estimatedMinutes,
      scheduledStartTime: scheduledStartTime,
      category: category,
      dependencyIds: dependencyIds ?? this.dependencyIds,
      milestoneId: milestoneId,
      isSensitive: isSensitive ?? this.isSensitive,
      fallbackTaskIds: fallbackTaskIds ?? this.fallbackTaskIds,
      executionMetadata: executionMetadata ?? this.executionMetadata,
      targetDeviceId: targetDeviceId ?? this.targetDeviceId,
    );
  }
}

/// Represents a significant achievement marker within a plan.
@immutable
class KnightMilestone {
  const KnightMilestone({
    required this.id,
    required this.title,
    required this.isReached,
    this.targetDate,
  });

  final String id;
  final String title;
  final bool isReached;
  final DateTime? targetDate;
}

/// A structured sequence of tasks and milestones to achieve an objective.
@immutable
class KnightPlan {
  const KnightPlan({
    required this.id,
    required this.title,
    required this.goalId,
    required this.tasks,
    this.milestones = const [],
    required this.status,
    required this.createdAt,
    this.updatedAt,
  });

  final String id;
  final String title;
  final String goalId;
  final List<KnightTask> tasks;
  final List<KnightMilestone> milestones;
  final MissionStatus status;
  final DateTime createdAt;
  final DateTime? updatedAt;
}

/// The consolidated output of a planning cycle.
@immutable
class PlanningResult {
  const PlanningResult({
    required this.dailyPlan,
    required this.activePlans,
    required this.suggestedTasks,
    required this.timestamp,
    required this.reasoningUsed,
  });

  /// The prioritized plan for the current day.
  final KnightPlan dailyPlan;

  /// All currently active strategic plans.
  final List<KnightPlan> activePlans;

  /// New tasks suggested based on recent reasoning.
  final List<KnightTask> suggestedTasks;

  final DateTime timestamp;

  /// Pointers to the reasoning that influenced this plan.
  final ReasoningResult reasoningUsed;
}
