class AppRoutes {
  const AppRoutes._();

  static const splash = '/';
  static const welcome = '/welcome';
  static const auth = '/auth';
  static const onboarding = '/onboarding';
  static const launch = '/launch';
  static const dashboard = '/dashboard';
  static const account = '/account';
  static const voiceCapture = '/voice-capture';
  static const home = '/home';
  static const settings = '/settings';
  static const profile = '/profile';
  static const privacy = '/privacy';
  static const appUpdates = '/app-updates';
  static const learning = '/learning';
  static const memory = '/memory';
  static const journal = '/journal';
  static const timeline = '/timeline';
  static const search = '/search';
  static const integrations = '/integrations';
  static const automation = '/automation';
  static const sleep = '/sleep';
  static const work = '/work';
  static const finance = '/finance';
  static const fitness = '/fitness';
  static const mission = '/mission';
  static const planner = '/planner';
  static const knight = '/knight';
  static const lifeAtlas = '/life-atlas';
  static const knowledgeVault = '/knowledge-vault';
  static const knowledgeGraph = '/knowledge-graph';
  static const myPlace = '/my-place';
  static const myData = '/my-data';
  static const documents = '/documents';
  static const health = '/health';
  static const importCenter = '/import-center';
  static const connectors = '/connectors';
  static const discovery = '/discovery';
  static const intelligence = '/intelligence';
}
